logging:
  level: debug
  format: json

http_server:
  listen: ":8080"
  read_timeout: 10s
  read_header_timeout: 5s
  write_timeout: 10s

queues:
  - name: test_messages
    max_messages: 100
    max_subscribers: 3

shutdown_timeout: "10s"